name=IOT_Modem_HAL
version=0.1.0
author=kkfranco98
maintainer=kkfranco98
sentence=Simple hardware abstraction layer for powering and controlling IoT cellular modems
paragraph=Tiny HAL for IoT cellular modems that handles power on, reset, power off and status pins. Designed to remove the hassle of modem startup sequences and simplify integration with libraries like TinyGSM
category=Communication
architectures=*
license=MIT
url=https://github.com/kkfranco98/IOT_Modem_HAL
