name=IOT_Modem_HAL
version=0.1.0
author=kkfranco98
maintainer=kkfranco98
sentence=
paragraph=Hardware Abstraction Layer for IOT Modem
category=
architectures=*
license=MIT
url=https://github.com/kkfranco98/...
